### PR TITLE
Feature/battery status

### PR DESCRIPTION
**Pull request by robertdbruijne**
Added ros topic /battery_voltage where input voltage into Roboclaw is published per Roboclaw. Sends RoboclawBatteryMessage with [int32 index; float32 battery_voltage].

### CODE REVIEW

**Comment by robertdbruijne** [comment]
Topic battery_voltage is now a topic with [int32 index; float32 battery_voltage] to allow for multiple Roboclaws (index indicates number of Roboclaw). Is this the correct way or should I implement multiple topics for each Roboclaw, each as simple float32 topic?

**Comment by MCFurry** [comment]
Nice work thus far! 
If I understand correctly, the Roboclaw boards can be chained together? In this case a single ros-node will communicate with multiple boards over a single UART connection? And hence, potentially publish multiple voltage?
In that case I would make your message contain two arrays that can be filled.

Take a look for example at http://docs.ros.org/melodic/api/sensor_msgs/html/msg/JointState.html
The jointstate message is typically a message with arrays that you can fill depending on how much you have to report.

**Comment by Timple** [comment]
I think it is most important to adhere to the methods / syntax used in this repository.
I notice from you launch files there is a diffdrive_node and a roboclaw_node. Probably the first can have two motors and the latter one?

Also in the [`msg`](https://github.com/nobleo/roboclaw/blob/master/msg/RoboclawMotorVelocity.msg) directory I see two messages which have the same problem as your voltage reading:
Single encoder per roboclaw, single velocity per roboclaw and a single voltage per roboclaw.

So solve your voltage problem the same as they did. New message with `index`, `mot1_volt` and `mot2_volt`. Just to be consistent.

If you want to support chaining more roboclaws that would be a new feature and deserves a new pull request.

**Comment by robertdbruijne** [comment]
@Timple The current implementation is equal to the source implementation, with an index and and a voltage per Roboclaw (which is the input voltage). Each Roboclaw can control 2 motors, but has one battery input voltage. Multiple Roboclaw support is possible because the 'index' message is automatically increased when the in the message, which is why (I think) it initially was created. When I implement a suggestion JointStatePublisher as @MCFurry proposes, I will deviate from the source code. joint_state_publisher looks nice to implement! However, I will deviate from the source code then. Is this a problem? Now velocities and motor enc's are published on separate topics. Shall I remove those and implement state_publisher instead? I can also implement the applied effort via current calculations, so this could work.

**Pull request closed without merging**
